### ISSUE TITLE
"Invalid Host header": --host 0.0.0.0 not working with public ip, due to webpack-dev-server v2.4.3 security fix

### ISSUE THREAD

**Issue by luckynum7** [centrual/cordova-template-framework7-vue-webpack#38]
Hi guys,

I'm still use the `1.0.9` version template, after reinstall my pc and checkout my projects. I ran into an error on my test phone, `Invalid Host header` with a white background.

As per https://github.com/webpack/webpack-dev-server/issues/882#issuecomment-296436511, and https://github.com/webpack/webpack-dev-server/releases/tag/v2.4.3,

- Requests are not blocked when `Host` doesn't match listening host or `public` option.
- Requests to `localhost` or `127.0.0.1` are not blocked.

the config in `webpack.config.js` (https://github.com/centrual/cordova-template-framework7-vue-webpack/blob/master/template_src/webpack.config.js#L105)
```js
host: "0.0.0.0",
```

My due date is today, so I just add `disableHostCheck: true` under that line to continue the work.

Hope you'll find a better way to fix this. : )

**Comment by centrual** [comment]
It's already fixed in 1.0.12 also current version is 1.1.1 😄 

Have a great day!

**Comment by tstikvoort** [comment]
I'm still experiencing this issue. Cordova version 6.5.0, node 6.9.2, clean install of your template. The app con't connect. After I set `disableHostCheck: true`, the app still doesn't work, although the app is served at `localhost:8081`.

**Comment by sunflowerlb** [comment]
me too!

**Comment by rajahimanath** [comment]
Has this issue ever been resolved??

**Comment by VictorioBerra** [comment]
BUMP. Why can we not override this yet? Trying to use ngrok.

**Comment by dineshmaths1** [comment]
Am using Angular CLI: 6.2.2 , Node: 8.11.1 and OS: darwin x64 This is my etc hosts 127.0.0.1 dinesh.mysocialapi.com

This is my comment node_modules/@angular/cli/bin/ng serve --host 0.0.0.0 --disableHostCheck true

am getting this error how to fix ? Loading failed for the with source “http://dinesh.mysocialapi.com/vendor.js”. dinesh.mysocialapi.com:34
